from enum import Enum


class YellowLetters(Enum):
        a = "_A_"
        b = "_B_"
        c = "_C_"
        d = "_D_"
        e = "_E_"
        f = "_F_"
        g = "_G_"
        h = "_H_"
        i = "_I_"
        j = "_J_"
        k = "_K_"
        l = "_L_"
        m = "_M_"
        n = "_N_"
        o = "_O_"
        p = "_P_"
        q = "_Q_"
        r = "_R_"
        s = "_S_"
        t = "_T_"
        u = "_U_"
        v = "_V_"
        w = "_W_"
        x = "_X_"
        y = "_Y_"
        z = "_Z_"